In [36]:
import joblib
import numpy as np

In [37]:
model = joblib.load('Hinselmann_model')

In [38]:
info = np.array([15, 6, 3, 51, 17, 0, 7, 0])

In [39]:
model.predict(info.reshape(1,8))

array([0], dtype=int64)

In [40]:
for i in info:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [41]:
import pandas as pd

In [42]:
df = pd.read_csv("Clean Data_2.csv")

In [43]:
df

Unnamed: 0  Age  Number of sexual partners  First sexual intercourse  \
0             0   18                        4.0                      15.0   
1             1   15                        1.0                      14.0   
2             2   34                        1.0                      17.0   
3             3   52                        5.0                      16.0   
4             4   46                        3.0                      21.0   
..          ...  ...                        ...                       ...   
851         851   34                        3.0                      18.0   
852         852   32                        2.0                      19.0   
853         853   25                        2.0                      17.0   
854         854   33                        2.0                      24.0   
855         855   29                        2.0                      20.0   

     Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                   1.0     0.0             0.0                  0.0   
1                   1.0     0.0             0.0                  0.0   
2                   1.0     0.0             0.0                  0.0   
3                   4.0     1.0            37.0                 37.0   
4                   4.0     0.0             0.0                  0.0   
..                  ...     ...             ...                  ...   
851                 0.0     0.0             0.0                  0.0   
852                 1.0     0.0             0.0                  0.0   
853                 0.0     0.0             0.0                  0.0   
854                 2.0     0.0             0.0                  0.0   
855                 1.0     0.0             0.0                  0.0   

     Hormonal Contraceptives  Hormonal Contraceptives (years)  ...  STDs:HIV  \
0                        0.0                             0.00  ...       0.0   
1                        0.0                             0.00  ...       0.0   
2                        0.0                             0.00  ...       0.0   
3                        1.0                             3.00  ...       0.0   
4                        1.0                            15.00  ...       0.0   
..                       ...                              ...  ...       ...   
851                      0.0                             0.00  ...       0.0   
852                      1.0                             8.00  ...       0.0   
853                      1.0                             0.08  ...       0.0   
854                      1.0                             0.08  ...       0.0   
855                      1.0                             0.50  ...       0.0   

     STDs: Number of diagnosis  Dx:Cancer  Dx:CIN  Dx:HPV  Dx  Hinselmann  \
0                            0          0       0       0   0           0   
1                            0          0       0       0   0           0   
2                            0          0       0       0   0           0   
3                            0          1       0       1   0           0   
4                            0          0       0       0   0           0   
..                         ...        ...     ...     ...  ..         ...   
851                          0          0       0       0   0           0   
852                          0          0       0       0   0           0   
853                          0          0       0       0   0           0   
854                          0          0       0       0   0           0   
855                          0          0       0       0   0           0   

     Schiller  Citology  Biopsy  
0           0         0       0  
1           0         0       0  
2           0         0       0  
3           0         0       0  
4           0         0       0  
..        ...       ...     ...  
851         0         0       0  
852         0         0       0  
853         0         1

In [62]:
df.iloc[6]

Unnamed: 0                          6.0
Age                                51.0
Number of sexual partners           3.0
First sexual intercourse           17.0
Num of pregnancies                  6.0
Smokes                              1.0
Smokes (years)                     34.0
Smokes (packs/year)                 3.4
Hormonal Contraceptives             0.0
Hormonal Contraceptives (years)     0.0
IUD                                 1.0
IUD (years)                         7.0
STDs                                0.0
STDs (number)                       0.0
STDs:condylomatosis                 0.0
STDs:syphilis                       0.0
STDs:HIV                            0.0
STDs: Number of diagnosis           0.0
Dx:Cancer                           0.0
Dx:CIN                              0.0
Dx:HPV                              0.0
Dx                                  0.0
Hinselmann                          1.0
Schiller                            1.0
Citology                            0.0


In [44]:
df.columns

Index(['Unnamed: 0', 'Age', 'Number of sexual partners',
       'First sexual intercourse', 'Num of pregnancies', 'Smokes',
       'Smokes (years)', 'Smokes (packs/year)', 'Hormonal Contraceptives',
       'Hormonal Contraceptives (years)', 'IUD', 'IUD (years)', 'STDs',
       'STDs (number)', 'STDs:condylomatosis', 'STDs:syphilis', 'STDs:HIV',
       'STDs: Number of diagnosis', 'Dx:Cancer', 'Dx:CIN', 'Dx:HPV', 'Dx',
       'Hinselmann', 'Schiller', 'Citology', 'Biopsy'],
      dtype='object')

In [45]:
X = df[['Age','Number of sexual partners',
       'First sexual intercourse', 'Num of pregnancies','Hormonal Contraceptives',
       'Hormonal Contraceptives (years)', 'IUD','Dx:Cancer']].values
y = df['Hinselmann'].values

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [60]:
predictions = model.predict(info.reshape(1,8))
predictions

array([0], dtype=int64)

In [48]:
confusion_matrix(predictions,y)

array([[811,   2],
       [ 10,  33]], dtype=int64)

In [49]:
accuracy_score(y,predictions)

0.985981308411215

In [50]:
classification_report(y,predictions)

'              precision    recall  f1-score   support\n\n           0       1.00      0.99      0.99       821\n           1       0.77      0.94      0.85        35\n\n    accuracy                           0.99       856\n   macro avg       0.88      0.97      0.92       856\nweighted avg       0.99      0.99      0.99       856\n'

In [57]:
pd.DataFrame(X[1].reshape(1,8),columns=['Age','Number of sexual partners',
       'First sexual intercourse', 'Num of pregnancies','Hormonal Contraceptives',
       'Hormonal Contraceptives (years)', 'IUD','Dx:Cancer'])

Age  Number of sexual partners  First sexual intercourse  \
0  15.0                        1.0                      14.0   

   Num of pregnancies  Hormonal Contraceptives  \
0                 1.0                      0.0   

   Hormonal Contraceptives (years)  IUD  Dx:Cancer  
0                              0.0  0.0        0.0

In [ ]:
pd.DataFrame